"""empty message

Revision ID: 618465b619fb
Revises: f609aafb94d9
Create Date: 2020-09-10 12:16:45.355526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618465b619fb'
down_revision = 'f609aafb94d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
